DROP TABLE IF EXISTS employees;
-- DROP TABLE IF EXISTS role;
-- DROP TABLE IF EXISTS departments;


CREATE TABLE employees(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
description TEXT,
role_id INT NOT NULL,
manager_id INT NOT NULL
);

-- CREATE TABLE role(
-- id INTEGER AUTO_INCREMENT PRIMARY KEY,
-- title VARCHAR(50) NOT NULL,
-- salary DECIMAL(7,2) NOT NULL,
-- department_id INT NOT NULL
-- );

-- CREATE TABLE departments(
-- id INTEGER AUTO_INCREMENT PRIMARY KEY,
-- name VARCHAR(30) NOT NULL,
-- );